name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Clean cache
      run: npm cache clean --force
      
    - name: Install Dependencies
      run: npm ci

      

    - name: Build
      run: npm run build
    
    - name: Deploy
      env:
        DT_APP_OAUTH_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        DT_APP_OAUTH_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }}
      run: npm run deploy
